---
- hosts: devserver
  become: yes
  ignore_errors: yes
  tasks:
    - name: creating user
      user:
        name: gaius
        comment: gaius admin
        shell: /bin/bash
    - name: create a file
      file:
        path: /tmp/ansible.txt
        state: touch
        mode: '0600'
    - name: create directory
      file:
        path: /tmp/dir
        state: directory
        mode: '0777'

    - name: install apache
      yum:
        name: httpd
        state: present
  
    - name: install finger
      package:
        name: finger
        state: present
      with_items:
        - wget
        - samba
        - java-8*
        - finger

